/* Kinetik storefront — demo catalog (no real media; placeholders by code).
   `unavailable` lists sold-out color|size combos. Use `${color}|*` for a whole
   colorway. `soldOut` (size list) is kept for back-compat with simple cards. */
window.KINETIK_PRODUCTS = [
  {
    id: 'shell-01', name: 'Shell-01 Hardshell', category: 'Outerwear', code: 'KX-SHELL-01',
    price: 336, compareAt: 420, badge: 'New Drop', rating: 4.6, reviews: 128,
    colors: [{ name: 'Volt', swatch: '#CCFF00' }, { name: 'Ink', swatch: '#0A0A0A' }, { name: 'Bone', swatch: '#EDEAE2' }],
    sizes: ['XS', 'S', 'M', 'L', 'XL'], soldOut: ['XS'],
    unavailable: ['Volt|XS', 'Ink|XS', 'Bone|XS', 'Volt|XL', 'Bone|S'],
    lowStock: ['Volt|L'],
    blurb: '3-layer Gore-Tex shell engineered for movement. Laser-cut vents, magnetic storm placket, fully taped seams.',
    specs: [['Membrane', 'Gore-Tex 3L'], ['Weight', '480g'], ['Fit', 'Boxed regular'], ['Origin', 'Made in JP']],
  },
  {
    id: 'pant-02', name: 'Cargo Tech Pant', category: 'Bottoms', code: 'KX-PANT-02',
    price: 210, compareAt: null, badge: null, rating: 4.4, reviews: 64,
    colors: [{ name: 'Ink', swatch: '#0A0A0A' }, { name: 'Steel', swatch: '#7C8794' }],
    sizes: ['28', '30', '32', '34', '36'], soldOut: ['28'],
    unavailable: ['Ink|28', 'Steel|28', 'Steel|36'],
    lowStock: ['Ink|34'],
    blurb: 'Articulated 4-way stretch cargo with sealed zip pockets and a gusseted crotch for full range of motion.',
    specs: [['Fabric', 'Schoeller Dryskin'], ['Weight', '320g'], ['Fit', 'Tapered'], ['Origin', 'Made in PT']],
  },
  {
    id: 'aud-03', name: 'Field Monitors', category: 'Audio', code: 'KX-AUD-03',
    price: 290, compareAt: 340, badge: null, rating: 4.8, reviews: 212,
    colors: [{ name: 'Ink', swatch: '#0A0A0A' }, { name: 'Bone', swatch: '#EDEAE2' }],
    sizes: ['One Size'], soldOut: [],
    unavailable: [],
    lowStock: [],
    blurb: 'Closed-back reference monitors. 40mm beryllium-coated drivers, machined aluminium cups, 40h battery.',
    specs: [['Driver', '40mm Be'], ['Battery', '40h'], ['Codec', 'LDAC / aptX'], ['Weight', '286g']],
  },
  {
    id: 'tee-04', name: 'Box Tech Tee', category: 'Tops', code: 'KX-TEE-04',
    price: 78, compareAt: null, badge: null, rating: 4.3, reviews: 41,
    colors: [{ name: 'Bone', swatch: '#EDEAE2' }, { name: 'Ink', swatch: '#0A0A0A' }, { name: 'Volt', swatch: '#CCFF00' }],
    sizes: ['S', 'M', 'L', 'XL'], soldOut: [],
    unavailable: ['Volt|S', 'Volt|XL'],
    lowStock: ['Volt|M'],
    blurb: 'Heavyweight 240gsm supima jersey, boxed silhouette, bonded hem. The everyday base layer.',
    specs: [['Fabric', '240gsm Supima'], ['Fit', 'Boxed'], ['Care', 'Cold wash'], ['Origin', 'Made in PT']],
  },
  {
    id: 'bag-05', name: 'Sling 4L', category: 'Gear', code: 'KX-BAG-05',
    price: 145, compareAt: null, badge: 'New Drop', rating: 4.7, reviews: 88,
    colors: [{ name: 'Ink', swatch: '#0A0A0A' }, { name: 'Volt', swatch: '#CCFF00' }],
    sizes: ['One Size'], soldOut: [],
    unavailable: [],
    lowStock: ['Volt|One Size'],
    blurb: 'Weatherproof X-Pac sling with a magnetic Fidlock buckle and a hidden RFID pocket.',
    specs: [['Fabric', 'X-Pac VX21'], ['Volume', '4L'], ['Buckle', 'Fidlock'], ['Weight', '210g']],
  },
  {
    id: 'cap-06', name: 'Tech Logo Cap', category: 'Gear', code: 'KX-CAP-06',
    price: 64, compareAt: null, badge: null, rating: 4.2, reviews: 33,
    colors: [{ name: 'Ink', swatch: '#0A0A0A' }, { name: 'Steel', swatch: '#7C8794' }],
    sizes: ['One Size'], soldOut: [],
    unavailable: ['Steel|*'],
    lowStock: [],
    blurb: 'Unstructured 6-panel in coated ripstop with a debossed volt logo and a recycled webbing strap.',
    specs: [['Fabric', 'Coated ripstop'], ['Panels', '6'], ['Strap', 'Recycled web'], ['Origin', 'Made in VN']],
  },
  {
    id: 'jkt-07', name: 'Liner Vest', category: 'Outerwear', code: 'KX-JKT-07',
    price: 248, compareAt: 310, badge: null, rating: 4.5, reviews: 57,
    colors: [{ name: 'Ink', swatch: '#0A0A0A' }, { name: 'Bone', swatch: '#EDEAE2' }],
    sizes: ['S', 'M', 'L', 'XL'], soldOut: ['S'],
    unavailable: ['Ink|S', 'Bone|S', 'Bone|XL'],
    lowStock: ['Ink|M'],
    blurb: 'PrimaLoft Gold liner vest that packs into its own chest pocket. Wear solo or zip into the Shell-01.',
    specs: [['Fill', 'PrimaLoft Gold'], ['Weight', '240g'], ['Packs to', '1L'], ['Origin', 'Made in VN']],
  },
  {
    id: 'aud-08', name: 'Buds Pro', category: 'Audio', code: 'KX-AUD-08',
    price: 180, compareAt: null, badge: null, rating: 4.6, reviews: 149,
    colors: [{ name: 'Ink', swatch: '#0A0A0A' }, { name: 'Bone', swatch: '#EDEAE2' }],
    sizes: ['One Size'], soldOut: [],
    unavailable: ['Bone|*'],
    lowStock: [],
    blurb: 'Active-noise-cancelling earbuds with a machined case, 8h playback, and dual-device handoff.',
    specs: [['Driver', '11mm'], ['ANC', '−42dB'], ['Battery', '8h + 24h'], ['Weight', '4.8g']],
  },
];
