import { registerSection } from "../registry";
import { RichText } from "./rich-text";
import { AnnouncementBar } from "./announcement-bar";
import { Header } from "./header";
import { Hero } from "./hero";
import { Slideshow } from "./slideshow";
import { Marquee } from "./marquee";
import { FeaturedCollection } from "./featured-collection";
import { Footer } from "./footer";
import { ImageWithText } from "./image-with-text";
import { Multicolumn } from "./multicolumn";
import { Newsletter } from "./newsletter";
import { CollectionList } from "./collection-list";
import { MainProduct } from "./main-product";
import { RelatedProducts } from "./related-products";
import { MainCollection } from "./main-collection";
import { MainSearch } from "./main-search";
import { MainCart } from "./main-cart";
import { MainBlog } from "./main-blog";
import { MainArticle } from "./main-article";
import { MainPage } from "./main-page";
import { ContactForm } from "./contact-form";
import { MainAccount } from "./main-account";
import { MainPassword } from "./main-password";
import { MainGiftCard } from "./main-gift-card";
import { FeaturedProduct } from "./featured-product";
import { CollapsibleContent } from "./collapsible-content";
import { LogoList } from "./logo-list";
import { Testimonials } from "./testimonials";
import { ImageGallery } from "./image-gallery";
import { Video } from "./video";
import { BlogPosts } from "./blog-posts";
import { CustomLiquid } from "./custom-liquid";
import { MapSection } from "./map";

export function registerSections(): void {
  registerSection("rich-text", RichText);
  registerSection("announcement-bar", AnnouncementBar);
  registerSection("header", Header);
  registerSection("hero", Hero);
  registerSection("slideshow", Slideshow);
  registerSection("marquee", Marquee);
  registerSection("featured-collection", FeaturedCollection);
  registerSection("footer", Footer);
  registerSection("image-with-text", ImageWithText);
  registerSection("multicolumn", Multicolumn);
  registerSection("newsletter", Newsletter);
  registerSection("collection-list", CollectionList);
  registerSection("main-product", MainProduct);
  registerSection("related-products", RelatedProducts);
  registerSection("main-collection", MainCollection);
  registerSection("main-search", MainSearch);
  registerSection("main-cart", MainCart);
  registerSection("main-blog", MainBlog);
  registerSection("main-article", MainArticle);
  registerSection("main-page", MainPage);
  registerSection("contact-form", ContactForm);
  registerSection("main-account", MainAccount);
  registerSection("main-password", MainPassword);
  registerSection("main-gift-card", MainGiftCard);
  registerSection("featured-product", FeaturedProduct);
  registerSection("collapsible-content", CollapsibleContent);
  registerSection("logo-list", LogoList);
  registerSection("testimonials", Testimonials);
  registerSection("image-gallery", ImageGallery);
  registerSection("video", Video);
  registerSection("blog-posts", BlogPosts);
  registerSection("custom-liquid", CustomLiquid);
  registerSection("map", MapSection);
}

registerSections();
